### ISSUE TITLE
长连接问题

### ISSUE THREAD

**Issue by fenghoer** [mix-php/mix#12]
RedisPersistent，PdoPersistent这两个貌似都没有真的用到长连接，redis及mysql的连接走的php扩展的方式连接的，redis长连接的明显特征是$redis->pconnect($this->host, $this->port)，mysql长连接的特征是array(PDO::ATTR_PERSISTENT => true).
然后，虽然connect对象存储起来了，但把对象存储起来就是长连接吗？

**Comment by onanying** [comment]
你测试一下就能知道了，上面你提到的两种方式是传统方式，是fpm/apache这种方式由fpm/apache帮php实现的，而swooleHttpServer则是一个常驻执行的CLI程序，也就是说，任何client连接如果你不主动去关闭，都是长连接。

**Comment by 52fhy** [comment]
@onanying 您好，redis连接有些疑问：
框架里我看了是根据抛异常重新连接，那么问题如下：
1、 连接超时的情况，会等待几秒钟才抛异常，如果这时候刚好有大量访问，会引发很大的问题；
2、异常里检测用的字符串好像并不全，例如`read error on connection`这种就没有。
3、`ping()`是否也可以加入到检测里面：每次获取redis对象时，除了判断是否为null，使用ping命令看看返回值是否是`+PONG`，不是的话也重连下。

**Comment by onanying** [comment]
@52fhy 
第一种情况，redis已经出现问题，在任何框架搭建的系统中，都会引发很大的问题，
第二种情况，所以需要大家一起来完善，参与到开源当中来
第三种情况，当连接被数据库主动断开时，ping是调用不了的，直接会报错。
