### ISSUE TITLE
2.2版本 UDP服务器会重复执行处理接收到的数据

### ISSUE THREAD

**Issue by yancanchen** [mix-php/mix#123]
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/9741362/201478441-f52bec9e-6de6-4402-a1d7-137b40c68b1b.png">
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/9741362/201478490-5b999951-a27b-49f0-a2a1-722430de33cc.png">
1.启动服务器的时候，直接出现3个start server
2.然后接到一个客户端请求，直接被重复执行三次。

**Comment by yancanchen** [comment]
https://github.com/mix-php/mix-skeleton 使用是这个脚手架

**Comment by onanying** [comment]
3个 server start，看着像是启动了3个
