### ISSUE TITLE
能增加TCP和UDP的服务么？

### ISSUE THREAD

**Issue by jiajiale** [mix-php/mix#13]
现在做物联网相关应用使用TCP和UDP比较多，能增加TCP和UDP的服务么？

**Comment by onanying** [comment]
TCP/UDP 都要自定义协议，这两种都不太好封装为开箱即用的方案，其实 mix 已经提供了很多 CLI 开发的中需要的大部分组件，如果真的要写 TCP/UDP 建议根据 swoole 文档，封装一个 Tcp/UdpServer 类即可。

**Comment by xuqiang76** [comment]
是啊  swoole 直接用就行了

**Comment by onanying** [comment]
新版本v2已经增加

**Comment by Hao-Wu** [comment]
> 新版本v2已经增加

文档里似乎还没有同步更新？没找到TCP/UDP相关的说明。
