### ISSUE TITLE
不对视图模块加载, 这样会不会进一步提升性能?

### ISSUE THREAD

**Issue by zl939144892** [mix-php/mix#32]
有一个不成熟的提议:
可以出一个纯API的版本, 或者在配置里有一个开关.
这样把框架用于纯API, 不对视图模块加载, 这样会不会进一步提升性能?
如果我说错了请见谅.

**Comment by onanying** [comment]
mixphp 就是为 api 而生的，视图模块不使用完全不会损耗一点性能。
