### ISSUE TITLE
HttpServer里onRequest全局变量问题

### ISSUE THREAD

**Issue by 52fhy** [mix-php/mix#37]
这里直接把`$request`, `$response`放在全局变量`\Mix::app()`，多个用户并发请求，变量不是污染（被后续变量覆盖了）了吗？不应该每个请求来创建一个`\Mix`对象吗？

**Comment by onanying** [comment]
1. 首先 mix 现在是采用的阻塞同步模式，在这种模式中，一个请求只会在同一个进程，只有在 onRequest 结束后，这个进程才能接收其他请求，而 mix 的组件都有实现 onRequestStart onRequestEnd 事件，所以没有变量污染问题，反而，因为是全局变量，组件常驻于内存，无需初始化，才有比其他框架高很多的性能。
2. 当 mix 开启协程时 (我还在开发)，一个进程同一时刻会处理N个请求，这个时候组件就会有变量污染问题了，但是我为组件开发了协程隔离机制，会在不同的协程内生成不同的组件，但用户确感知不到，因为使用的方法与阻塞同步不变。

**Comment by 52fhy** [comment]
@onanying 感谢您的耐心解答。对于第一点，我看到swoole是基于epoll实现IO复用的，那么同一个进程里接收多个客户端请求，这时候其实也是阻塞执行的？可以这么理解吗？然后第二点这个特性很期待！
