### ISSUE TITLE
能兼容 think-orm 吗

### ISSUE THREAD

**Issue by yangguangwuwu** [mix-php/mix#38]
能兼容think-orm吗这样更方便 中小企业使用

**Comment by onanying** [comment]
可以接入的，但是只能是常驻同步模式，在常驻协程模式是不可以的，因为 think-orm 的代码里使用了大量的全局变量，存在协程的全局变量污染问题，但是同步模式不影响，后面我会提供一个 composer 库，让用户可直接接入 think-orm。

**Comment by yangguangwuwu** [comment]
谢谢   大佬

**Comment by onanying** [comment]
根据文档 https://www.kancloud.cn/onanying/mixphp1/772135 接入，需使用 mixphp v1.1.0 最新版本。

**Comment by FireSoil** [comment]
我问下 mixphp 2.0 常驻同步模式下可以使用 think-orm 么？

**Comment by onanying** [comment]
可以的，接入方法需要借助 composer.json 的 files 字段的功能 https://github.com/mix-php/mix/blob/master/composer.json#L59，因为 V2 把 V1 的初始化功能取消了，也就是说之前 V1 初始化的代码写到一个 php 文件中，然后在 composer files 中引用即可。
