### ISSUE TITLE
可否支持无限路由

### ISSUE THREAD

**Issue by jinmarcus** [mix-php/mix#41]
手册里路由只能手动定义
能不能自由定义无限路由？
不需要像手册那样

如果我有多层级，比如 http://site.com/api/member/info/account/index
类似这样的，层级很多，如果按照手册的，需要一个一个去定义，那非常的不方便。

```
// 路由规则
'rules'          => [
    // 只有GET或POST才可访问
	'GET|POST api/:controller/:action' => ['api/:controller', ':action'],
],
```

**Comment by onanying** [comment]
这个我在设计之初就思考过，而且改动过多次，最初是支持你说的无限路由的，后来我修改成了现在的样子。
原因：
路由歧义，如：api/index, 到底是 api 控制器的 index 方法，还是 api/index 控制器省略了 index 方法没有写，这个在每一级路由都有这个问题，当然这个问题当时我解决了，就像其他 mvc 框架样，按优先级遍历判断文件，但是极大的降低了性能，且路由实现代码非常繁琐，做为一个轻量级框架，我觉得这个无法忍受，然后我根据实际场景分析，现有的项目通常路由大部分都只有两级+3级，因为过长的路由并不友好，而现有 mix 设计的路由，每增加一级路由只需定义一个通用路由即可，也就是说通常一个项目也就只需几条路由即可完成，已经在性能与实用做到了非常好的平衡了。

回到你的问题：

你需要规划简化你的路由，层级不应该太多，当然你如果觉得合适，每一级定义一个通用路由即可，也不费多少时间，但带来的是 N 倍于其他框架的路由性能。

**Comment by onanying** [comment]
```
// 路由规则
'rules'          => [
    // 一级路由
    ':controller/:action' => [':controller', ':action', 'middleware' => ['Before']],
    // 二级路由
    ':second/:controller/:action' => [':second/:controller', ':action', 'middleware' => ['Before']],
    // 三级路由
    ':third/:second/:controller/:action' => [':third/:second/:controller', ':action', 'middleware' => ['Before']],
],
```
