### ISSUE TITLE
Use user sessions with multiple servers? 

### ISSUE THREAD

**Issue by zilveer** [mix-php/mix#44]
Hi everyone,
a question can mix-php handle user sessions through multiple servers (front end ) connected to one database server ?

I am thinking of that laravel can handle it since one can store sessions in the database,  is this possible to do the same with mix-php ? 

Regards

**Comment by onanying** [comment]
The mix's session is stored in redis and does not use PHP's built-in session, which is completely different from laravel.

**Comment by zilveer** [comment]
@onanying 
Thx for to reply.
Is there any way to store the user sessions among multiple servers for front end ? I mean in the end we will be using load balancing and that is why it is important to be able have sessions in DB.
Or is there any other way to solve in it mix-php ?

**Comment by onanying** [comment]
The mix session is based on redis and supports load balancing.

**Comment by zilveer** [comment]
@onanying that means the if I use mix-pho there is no other way for me to share the user sessions amount the multiple servers if I don't create my own session handler right ?
Is there any plan to add DB session handler soon for mix-php soon ?
