### ISSUE TITLE
协程模式下数据库主从分离怎么做？

### ISSUE THREAD

**Issue by chenhui1221** [mix-php/mix#48]
mixphp2.0版本
数据库主从 看作者是 用于常驻进程模式。如果协程模式怎么实现呢？

**Comment by onanying** [comment]
mysql代理

**Comment by chenhui1221** [comment]
有demo参考么？ 连接池这一块，也需要重新弄吗？

**Comment by onanying** [comment]
https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&rsv_idx=1&tn=baidu&wd=mysql-proxy&oq=mysql%25E4%25BB%25A3%25E7%2590%2586&rsv_pq=d6a3b9e0000743ad&rsv_t=4f94l3HxL3%2B0hra2xkb0k7NxSNGCv00l3KYipsXgWfj%2B9skbJ%2FNQv%2BkGPhM&rqlang=cn&rsv_enter=0&rsv_sug3=2&rsv_sug1=2&rsv_sug7=100&rsv_n=2&inputT=520&rsv_sug4=577

**Comment by chenhui1221** [comment]
哦， 我要表达的不是mysql 配置方面。 而是代码层，怎么切换。比如我有主库，从库。查询走从库。更新插入，走主库。  或者某个语句指定走主库或从库。    我看作者Mix\Database\MasterSlave\PDOConnection 组件 ，场景说 只用常驻同步模式。 协程模式怎么实现这个呢？

**Comment by onanying** [comment]
MasterSlave 不能使用在协程中，为什么我不支持，是因为协程需要使用连接池，而连接池本身已经让连接非常多了，再加上主从的话，单进程连接数会非常夸张，所以在代码中实现主从变的非常的不适合。

**Comment by chenhui1221** [comment]
作者其实也可以设计下协程模式下的读写分离。 毕竟用中间件还是有很多不便的地方。  作者已经开发了这套框架，让许多phper能够用以前的方式写出高性能的代码。   估计有很大部分是喜欢用协程模式的，但是协程下 数据库读写分离 功底不好， 又不好实现。
