### ISSUE TITLE
WebSocket怎么指定给fd人发消息

### ISSUE THREAD

**Issue by litaonet** [mix-php/mix#49]
WebSocket怎么指定给fd人发消息，
app()->ws->push($frame);是发送给谁？

**Comment by onanying** [comment]
当前连接，就是当前与服务器建立连接的客户端

**Comment by litaonet** [comment]
如果有100个人与服务器建立连接，我怎么区分那个是那个？还有如何判断exist客户端是否存在

**Comment by onanying** [comment]
你仔细理解我写的 demo ：https://github.com/mix-php/mix/tree/master/applications/websocket/src
