### ISSUE TITLE
按照think-orm 接入的方式，接入了laravel ORM时，首次访问接口报错

### ISSUE THREAD

**Issue by superlangs** [mix-php/mix#50]
接入了laravel ORM时，报 PDO::prepare(): send of 65 bytes failed with errno=32 Broken pipe

**Comment by superlangs** [comment]
使用的mixphp版本是v1.1.1 ,

**Comment by onanying** [comment]
应该是没有正常连接吧，think-orm 是可以的，理论上 laravel ORM 只要配置正确应该也是可以的，但只能在同步编程中使用。

**Comment by superlangs** [comment]
我配置的是同步的模式，错误只发生在第一次访问接口的时候，后续都是正常的，网上搜索了下说是 mysql 配置下连接timeout 的时间，我配置成了一小时，但是还是没用

**Comment by superlangs** [comment]
感觉像是连接超时之后失效了，重新访问接口，就好了

**Comment by onanying** [comment]
那就应该是laravel orm 没有断线重连机制，think-orm 是有的

**Comment by superlangs** [comment]
laravel 的 ORM是有断线重连的机制的，而断线MySQL会报 “MySQL server has gone away”的错误，但是现在报错的信息是 PDO::prepare(): send of 65 bytes failed with errno=32 Broken pipe

**Comment by onanying** [comment]
断线的情况比你想想的要多的多，网关错误只是最常见的一种 https://github.com/mix-php/mix-database/blob/master/src/Persistent/PDOConnection.php#L113

**Comment by superlangs** [comment]
是的，我看过laravel断线重连的代码，都是包含这些的，
![image](https://user-images.githubusercontent.com/49265759/55926793-4e706b80-5c45-11e9-84bb-986d96cc3bee.png)

**Comment by superlangs** [comment]
附上我对接laravel ORM 的代码
![image](https://user-images.githubusercontent.com/49265759/55926904-b8891080-5c45-11e9-8d97-d1a45e7d824b.png)

**Comment by onanying** [comment]
解决不了的话，建议还是接入 think-orm 吧，那个我测试是通过的。
