### ISSUE TITLE
守护程序 daemon websocket 广播推送demo

### ISSUE THREAD

**Issue by chenhui1221** [mix-php/mix#52]
守护程序，如何 websocket 广播推送，大神能提供demo吗？ 需要在daemon 里 注册ws组件吗？

**Comment by onanying** [comment]
框架中本身包含有的 demo 就已经能实现了，
你先看 ws 的 join 代码，这里订阅了房间号的一个 redis 通道 `"room_{$model->roomid}"` ：https://github.com/mix-php/mix/blob/master/applications/websocket/src/Controllers/JoinController.php#L52

你只需要在 daemon 模块开一个进程往 redis 这个 `"room_{$model->roomid}"` 通道 publish，房间里的人都能收到。

后面的复杂需求你都能通过这种方式举一反三。

**Comment by chenhui1221** [comment]
恩。demo 里面看了，  是 通过redis的 发布/订阅实现的。 但是发布订阅，这个不好跟踪是否丢失，是否什么时候重发。

**Comment by chenhui1221** [comment]
比如给指定人 fd 发消息，   建立连接的时候， 我会将fd 跟 用户唯一标识绑定。 会维护这个绑定关系。      但是 我若在 守住进程那边定时 push，  我就不知道怎么弄了。 在websocket 应用里面， 倒是可以实现。在其他 模块不知道如何调用

**Comment by onanying** [comment]
需要你开动脑筋，工具大家都是这一些，业务都是自己设计，别人帮不了你，也不可能帮你。

**Comment by onanying** [comment]
定时 push 用定时器，框架有提供

**Comment by chenhui1221** [comment]
其实我就想问问这个框架的，Daemon 模块，如何优雅调用websocket 的发送 。因为这框架整个代码都是很舒服的。    至于业务，我也没想着让人帮。只是咨询下，其他模块如何调用websocket 的发送。

**Comment by onanying** [comment]
@chenhui1221 用定时器，往redis实例里 publish 数据即可。

**Comment by chenhui1221** [comment]
我也不知道是我的描述问题还是怎么的。 如果用redis，sub/pub.  客户端主动断开。 但是redis的sub 还存在该fd， 到时候pub 时候， 错误日志会 `NOTICE  swFactoryProcess_finish (ERROR 1005): connection[fd=2] does not exists`。
其次，如果我在Daemon模块，不用sub/pub.形式。根据业务，需要 push($fd) 指定的fd，这个框架好像是不支持这样吧。

**Comment by chenhui1221** [comment]
@onanying 还请指点下。
