### ISSUE TITLE
Did not register this component: db

### ISSUE THREAD

**Issue by Carl-Ellie** [mix-php/mix#53]
项目刚安装好运行起来，想试试数据库操作，提示我没有注册db组件
Did not register this component: db [0] Mix\Exception\ComponentException in /data/project/mix/vendor/mix/framework/src/Core/Container/Container.php line 43

**Comment by onanying** [comment]
框架默认是协程模式，而协程模式不能直接操作数据库，而需要使用连接池，所以默认代码没有配置db，而是配置了dbPool ，你需要了解文档的 https://www.kancloud.cn/onanying/mixphp2/889459 , https://www.kancloud.cn/onanying/mixphp2/988792 这两块内容
