### ISSUE TITLE
websocket demo 有问题。redis  sub 没法取消已经关闭的连接

### ISSUE THREAD

**Issue by chenhui1221** [mix-php/mix#54]
如题： 如果用redis，sub/pub. 客户端主动断开。 但是redis的sub 还存在该连接客户端， 到时候pub 时候， 错误日志会
` NOTICE swFactoryProcess_finish (ERROR 1005): connection[fd=2] does not exists`。 or
  ` NOTICE  swFactoryProcess_finish (ERROR 1004): send 70 byte failed, because connection[fd=31] is closed.`

然后再redis-cli   publish  返回的数量，也是发现这些关闭的还在订阅 频道

**Comment by onanying** [comment]
客户端主动端口，服务器会出发 hander 的 close 方法 https://github.com/mix-php/mix/blob/master/applications/websocket/src/Handlers/WebSocketHandler.php#L98 ，该方法有清除会话信息 `app()->tcpSession->clear();`，因为 redis 订阅的连接是放在里面的，所以会被清除，因此不会有你说的这个问题。

**Comment by chenhui1221** [comment]
你可以测试一下。 确实有这个问题。清除了该fd 的相关session。但是redis 端 的  sub 还在。 所以pub 的时候，他还是会推送，就会 提示  该fd 关闭 或不存在

**Comment by onanying** [comment]
提供下复现的详细过程

**Comment by onanying** [comment]
我测试了，无此问题，我启动ws后，加入房间，这个就订阅了 room_1010 ，然后刷新网页，这样连接就会断开，此时我再加入房间，如果之前的订阅还是，此时应该有两个连接监听 room_1010，然后我通过 redis-cli  执行 publish ，返回 1，证明只有一个连接在监听 room_1010，这个也证明刷新前的连接断开后，redis连接也断开了。

···
127.0.0.1:6379> publish room_1010 dfsdf
(integer) 1
···

**Comment by chenhui1221** [comment]
websocket 我又测了一遍是没这个问题了。 然后防着 这个在Tcp 服务里面， 也用同样的做法。
`  /**
     * 连接关闭
     * @param TcpConnection $tcp
     */
    public function close(TcpConnection $tcp)
    {
        app()->tcpSession->clear();
    }`
订阅过程代码
`  // 保存当前加入的房间
        app()->tcpSession->set('roomId', $app_id);
        // 重复加入处理
        if ($subConn = app()->tcpSession->get('subConn')) {
            $subConn->disconnect();
        }

        // 订阅房间的频道
        xgo(function () use ($app_id) {
            // 订阅房间的频道
            $subConn = RedisConnection::newInstance();
            app()->tcpSession->set('subConn', $subConn);
            try {
                ini_set('default_socket_timeout', -1);
                $subConn->subscribe(["room_{$app_id}"], function ($instance, $channel, $message) {
                    app()->log->info('push:' . print_r($message, true));
                    app()->tcp->send($message);
                });
            } catch (\Throwable $e) {
                // disconnect() 时会导致 subscribe 抛出错误
                app()->log->error('subscribe:' . $e->getMessage());
            }
        });
        // 给当前房间发送消息
        Timer::new()->after(100, function () use ($app_id, $response) {
            $conn = app()->redisPool->getConnection();
            $conn->publish("room_{$app_id}", $response);
            $conn->release();
        });`

例如 ，我订阅room_100002 频道。 打开一个tcp客户端进行连接进入。然后关闭。  然后重新开一个。redis 客户端
`127.0.0.1:6379> publish room_100002 1111122233
(integer) 2`

然后 tcp错误日志：
`NOTICE  swFactoryProcess_finish (ERROR 1005): connection[fd=1] does not exists.`

客户端关闭 tcphanlder  的close方法是进入了的， 我有打印。  但是sub 还是有 。

**Comment by onanying** [comment]
代码全部贴出来，要非常详细

**Comment by chenhui1221** [comment]
1.TcpHandler.php
`<?php

namespace Tcp\Handlers;

use Mix\Helper\JsonHelper;
use Mix\Tcp\Handler\TcpHandlerInterface;
use Mix\Tcp\TcpConnection;

/**
 * Class TcpHandler
 * @package Tcp\Handlers
 * @author liu,jian <coder.keda@gmail.com>
 */
class TcpHandler implements TcpHandlerInterface
{

    /**
     * 开启连接
     * @param TcpConnection $tcp
     */
    public function connect(TcpConnection $tcp)
    {
        // TODO: Implement open() method.
    }

    /**
     * 处理消息
     * @param TcpConnection $tcp
     * @param string $data
     */
    public function receive(TcpConnection $tcp, string $data)
    {
        // TODO: Implement message() method.
        // 主动退出处理
        if (base64_encode($data) == '//T//QYNCg==') {
            $tcp->disconnect();
        }
        // 解析数据
        $data = json_decode($data, true);
        if (!$data) {
            $response = [
                'jsonrpc' => '2.0',
                'error'   => [
                    'code'    => -32600,
                    'message' => 'Invalid Request',
                ],
                'id'      => null,
            ];
            $tcp->send(JsonHelper::encode($response) . "\n");
            return;
        }
        if (!isset($data['method']) || !isset($data['params']) || !isset($data['id'])) {
            $response = [
                'jsonrpc' => '2.0',
                'error'   => [
                    'code'    => -32700,
                    'message' => 'Parse error',
                ],
                'id'      => null,
            ];
            $tcp->send(JsonHelper::encode($response) . "\n");
            return;
        }
        // 路由到控制器
        list($controller, $action) = explode('.', $data['method']);
        $controller = \Mix\Helper\NameHelper::snakeToCamel($controller, true) . 'Controller';
        $controller = 'Tcp\\Controllers\\' . $controller;
        $action     = 'action' . \Mix\Helper\NameHelper::snakeToCamel($action, true);
        $response   = [
            'jsonrpc' => '2.0',
            'error'   => [
                'code'    => -32601,
                'message' => 'Method not found',
            ],
            'id'      => $data['id'],
        ];
        if (!class_exists($controller)) {
            $tcp->send(JsonHelper::encode($response) . "\n");
            return;
        }
        $controller = new $controller;
        if (!method_exists($controller, $action)) {
            $tcp->send(JsonHelper::encode($response) . "\n");
            return;
        }
        call_user_func([$controller, $action], $data['params'], $data['id']);
    }

    /**
     * 连接关闭
     * @param TcpConnection $tcp
     */
    public function close(TcpConnection $tcp)
    {
        // TODO: Implement close() method.
        app()->tcpSession->clear();
    }

}
`
2、Tcp\Controllers\JoinController
`<?php

namespace Tcp\Controllers;

use Mix\Core\Timer;
use Mix\Helper\JsonHelper;
use Mix\Redis\Coroutine\RedisConnection;


/**
 * Class JoinController
 * @package Tcp\Controllers
 * @author liu,jian <coder.keda@gmail.com>
 */
class JoinController
{

    /**
     * 加入房间
     * @param $params
     * @param $id
     */
    public function actionRoom($params, $id)
    {


        // 保存当前加入的房间
        app()->tcpSession->set('roomid', $params['app_id']);

        // 重复加入处理
        if ($subConn = app()->tcpSession->get('subConn')) {
            /** @var \Mix\Redis\Coroutine\RedisConnection $subConn */
            $subConn->disconnect();
        }

        // 订阅房间的频道
        xgo(function () use ($params) {
            // 订阅房间的频道
            $subConn = RedisConnection::newInstance();
            app()->tcpSession->set('subConn', $subConn);
            try {
                $subConn->subscribe(["room_{$params['app_id']}"], function ($instance, $channel, $message) {
                    app()->tcp->send($message."\r\n");  //测试发消息
                    app()->log->info('send'.$message);
                });
            } catch (\Throwable $e) {
                // disconnect() 时会导致 subscribe 抛出错误
            }
        });

        // 给当前房间发送消息
        Timer::new()->after(100, function () use ($params, $id) {
            $name     = app()->tcpSession->get('name');
            $response = JsonHelper::encode([
                'result' => [
                    'message' => "{$name} 加入 {$params['app_id']} 房间.",
                ],
                'id'     => $id,
            ], JSON_UNESCAPED_UNICODE)."\r\n";
            $conn     = app()->redisPool->getConnection();
            $conn->publish("room_{$params['app_id']}", $response);
            $conn->release();
        });
    }

}
`
3、连接tcp 服务器
`$client = new Swoole\Client(SWOOLE_SOCK_TCP, SWOOLE_SOCK_ASYNC);
$client->on("connect", function(swoole_client $cli) {
    $cli->send("{\"params\":{\"app_id\":100003},\"method\":\"join.room\",\"id\":2}\r\n");
});
$client->on("receive", function(swoole_client $cli, $data){
    echo "Receive: $data".PHP_EOL;
    

});
$client->on("error", function(swoole_client $cli){
    echo "error\n";
});
$client->on("close", function(swoole_client $cli){
    echo "Connection close\n";
});
$client->connect('127.0.0.1', 9508);
`

**Comment by onanying** [comment]
核心原因是 app()->tcpSession->clear() 无法断开正在使用中的连接(subscribe)，只能在 close 时手动关闭连接：

```
    /**
     * 连接关闭
     * @param TcpConnection $tcp
     */
    public function close(TcpConnection $tcp)
    {
        // TODO: Implement close() method.
        /** @var RedisConnection $subConn */
        $subConn = app()->tcpSession->get('subConn');
        $subConn && $subConn->disconnect();
        app()->tcpSession->clear();
    }
```

**Comment by chenhui1221** [comment]
测试完后，正常。
