### ISSUE TITLE
如何在一个Docker中同时启动http，ws

### ISSUE THREAD

**Issue by dickens7** [mix-php/mix#57]
* 希望在在一个docker中同时启动http服务和ws服务能实现么？ 还是说需要借助 Supervisor 这样的进程管理工具实现？

**Comment by onanying** [comment]
是的，借助 Supervisor

**Comment by dickens7** [comment]
有计划支持 不借助 Supervisor 支持同时启动多个服务么

**Comment by onanying** [comment]
没有，mix设计的服务都是独立的

**Comment by dickens7** [comment]
明白了， 感谢的你解答
