### ISSUE TITLE
建议增加redisCluster

### ISSUE THREAD

**Issue by xuebuctxy** [mix-php/mix#58]
现在只支持了redis主从，集群模式不支持，我们都要自己扩展，比较麻烦

**Comment by onanying** [comment]
redis主从也不支持，只有mysql主从

**Comment by xuebuctxy** [comment]
AbstractRedisConnection里面，增加一个集群模式的配置项
new \Redis(); 变成new \RedisCluster(); 就可以支持集群模式了。
我们可以封装，但框架里支持一下不是更好

**Comment by onanying** [comment]
因为用户想要的功能很多，我精力有限，我一直建议用户自己动手，然后提pr过来 (如果质量风格合适，我就接收了)
