### ISSUE TITLE
Mix\Redis\ExecuteListenerInterface

### ISSUE THREAD

**Issue by weiqiangxu** [mix-php/mix#59]
// 登陆方法
    public function actionLogin()
    {
        app()->session->set('name', '小华');

  }

Fatal error: Interface 'Mix\Redis\ExecuteListenerInterface' not found in D:\webserver\www\mix_new\applications\common\src\Listeners\RedisListener.php on line 12

**Comment by weiqiangxu** [comment]
请问我已经composer install之后为什么会出现redis类文件缺失呢

**Comment by onanying** [comment]
你安装了 master 版本吧，你要通过 composer 安装mix ，不要clone 

推荐使用 composer 安装。

`composer create-project mix/mix --prefer-dist`
