### ISSUE TITLE
在2.0.3 下composer update后报错

### ISSUE THREAD

**Issue by fenghoer** [mix-php/mix#60]
错误信息:
[error] 2019-06-17 23:34:18 <7045> [message] 视图文件不存在：/mnt/www/live/applications/http/views/errors/not_found.php
[code] 0 [type] Mix\Exception\ViewException
[file] /mnt/www/live/vendor/mix/http/src/View.php [line] 32

composer.json 里的配置:
"mix/framework": "~2.0.0",
    "mix/console": "~2.0.0",
    "mix/log": "~2.0.0",
    "mix/http": "~2.0.0",
    "mix/http-session": "~2.0.0",
    "mix/http-message": "~2.0.0",
    "mix/http-server": "~2.0.0",
    "mix/http-daemon": "~2.0.0",
    "mix/websocket": "~2.0.0",

**Comment by fenghoer** [comment]
下载release的2.0.6版本, 合并代码后已解决

**Comment by onanying** [comment]
是 v2.0.6 有一个不兼容改动，框架的全部不兼容改动都在文档 https://www.kancloud.cn/onanying/mixphp2/1099325 中有记录，可根据里面的内容更新。
