### ISSUE TITLE
路由规则bug，/news/article/{id}这种写法有问题

### ISSUE THREAD

**Issue by yupeng2015** [mix-php/mix#61]
`// 路由规则
'rules'          => [
	'/news/article/{id}.html' => ['News', 'Article'],
],`
这种路由规则，用app()->request->route('id')这种方式取不到。
必须这样写：app()->request->route('{id}')才能用，路由里面没有过滤掉'{}'

**Comment by onanying** [comment]
是的，下个版本会修复这个问题

**Comment by onanying** [comment]
已经修复，https://github.com/mix-php/http/releases/tag/v2.0.5
你可以 `composer update mix/http` 升级到 v2.0.5
如还有问题，反馈给我 @yupeng2015

**Comment by yupeng2015** [comment]
ok了，已解决
