### ISSUE TITLE
安装了SwooleFor

### ISSUE THREAD

**Issue by sjfxy** [mix-php/mix#62]
启动php swoolefor.phar -e "php /data/wwwroot/www.lua.qifeng/bin/mix-httpd start -c /data/wwwroot/www.lua.qifeng/http/config/httpd.php"  --ext=php,json,ini 
监控失败

**Comment by sjfxy** [comment]
./mix-httpd start -c ../applications/http/config/httpd.php  start 
                             _____
_______ ___ _____ ___   _____  / /_  ____
__/ __ `__ \/ /\ \/ /__ / __ \/ __ \/ __ \
_/ / / / / / / /\ \/ _ / /_/ / / / / /_/ /
/_/ /_/ /_/_/ /_/\_\  / .___/_/ /_/ .___/
                     /_/         /_/

APP            Name:      http
APP            Version:   0.0.0
Server         Name:      mix-httpd
Server         Version:   2.0.4
System         Name:      linux
PHP            Version:   7.2.21
Swoole         Version:   4.4.4
Framework      Version:   2.0.7
Coroutine      Mode:      enabled
Listen         Addr:      127.0.0.1
Listen         Port:      9501

**Comment by onanying** [comment]
你要先看看你执行的命令是不是能正常执行，先 `php /data/wwwroot/www.lua.qifeng/bin/mix-httpd start -c /data/wwwroot/www.lua.qifeng/http/config/httpd.php` 执行一下，看有没有错误。

**Comment by sjfxy** [comment]
OK






------------------ 原始邮件 ------------------
发件人: "LIU JIAN"<notifications@github.com>; 
发送时间: 2019年8月22日(星期四) 下午5:38
收件人: "mix-php/mix"<mix@noreply.github.com>; 
抄送: "神秘人物"<986244259@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [mix-php/mix] 安装了SwooleFor (#62)




你要先看看你执行的命令是不是能正常执行，先 php /data/wwwroot/www.lua.qifeng/bin/mix-httpd start -c /data/wwwroot/www.lua.qifeng/http/config/httpd.php 执行一下，看有没有错误。

**Comment by sjfxy** [comment]
[warning] 2019-08-22 17:45:28.989 <96355> [message] sub process exit too fast, sleep 2 seconds
[info] 2019-08-22 17:45:30.991 <96355> [message] executor start, exec: [php /data/wwwroot/www.lua.qifeng/mix/bin/mix-httpd start -c /data/wwwroot/www.lua.qifeng/mix/applications/http/config/httpd.php]
[info] 2019-08-22 17:45:30.992 <96355> [message] fork sub process, pid: 96383
[info] 2019-08-22 17:45:31.18 <96355> [message] sub process exit, pid: 96383, exitcode: 0, termsig: 0, stopsig: 0
[warning] 2019-08-22 17:45:31.18 <96355> [message] sub process exit too fast, sleep 2 seconds





------------------ 原始邮件 ------------------
发件人: "LIU JIAN"<notifications@github.com>; 
发送时间: 2019年8月22日(星期四) 下午5:38
收件人: "mix-php/mix"<mix@noreply.github.com>; 
抄送: "神秘人物"<986244259@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [mix-php/mix] 安装了SwooleFor (#62)




你要先看看你执行的命令是不是能正常执行，先 php /data/wwwroot/www.lua.qifeng/bin/mix-httpd start -c /data/wwwroot/www.lua.qifeng/http/config/httpd.php 执行一下，看有没有错误。

**Comment by sjfxy** [comment]
------------------ 原始邮件 ------------------
发件人: "LIU JIAN"<notifications@github.com>; 
发送时间: 2019年8月22日(星期四) 下午5:38
收件人: "mix-php/mix"<mix@noreply.github.com>; 
抄送: "神秘人物"<986244259@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [mix-php/mix] 安装了SwooleFor (#62)




你要先看看你执行的命令是不是能正常执行，先 php /data/wwwroot/www.lua.qifeng/bin/mix-httpd start -c /data/wwwroot/www.lua.qifeng/http/config/httpd.php 执行一下，看有没有错误。

**Comment by sjfxy** [comment]
php swoolefor.phar -e "php /data/wwwroot/www.lua.qifeng/mix/bin/mix-httpd start -c /data/wwwroot/www.lua.qifeng/mix/applications/http/config/httpd.php"  --watch=/data/wwwroot/www.lua.qifeng/mix --ext=json,php,ini


这样的命令有错误吗 




------------------ 原始邮件 ------------------
发件人: "LIU JIAN"<notifications@github.com>; 
发送时间: 2019年8月22日(星期四) 下午5:38
收件人: "mix-php/mix"<mix@noreply.github.com>; 
抄送: "神秘人物"<986244259@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [mix-php/mix] 安装了SwooleFor (#62)




你要先看看你执行的命令是不是能正常执行，先 php /data/wwwroot/www.lua.qifeng/bin/mix-httpd start -c /data/wwwroot/www.lua.qifeng/http/config/httpd.php 执行一下，看有没有错误。

**Comment by sjfxy** [comment]
Ok 了谢谢
