### ISSUE TITLE
数据库操作，同时使用 groupby 和 orderby 会出错语句报错

### ISSUE THREAD

**Issue by lushaobo** [mix-php/mix#64]
**版本:** 2.0.7
**代码如下：**
`DbPool::get()
->table('user')
->groupBy('id')
->orderBy('id', 'desc')
->get();
`

执行语句就会变成  **select * from user order by id desc group by id;**
其中 **order by** 在 **group by** 前面，所以会出现语句出错

**Comment by onanying** [comment]
@lushaobo   升级 database 库到 v2.0.6

```
composer update mix/database
```

解决没解决都回复我一下

**Comment by lushaobo** [comment]
已解决

**Comment by lushaobo** [comment]
已解决，能正常执行了。



450198236@qq.com
 
发件人： LIU JIAN
发送时间： 2019-10-24 13:11
收件人： mix-php/mix
抄送： lushaobo; Mention
主题： Re: [mix-php/mix] 数据库操作，同时使用 groupby 和 orderby 会出错语句报错 (#64)
@lushaobo 升级 database 库到 v2.0.6
composer update mix/database

解决没解决都回复我一下
