### ISSUE TITLE
2.1.0版本路由对于大量路由配置不好管理，建议同时支持注解路由

### ISSUE THREAD

**Issue by linklin7** [mix-php/mix#66]
2.1.0版本路由对于大量路由配置不好管理，建议同时支持注解路由，这样相对减少配置，同时更灵活！

附swoft框架注解：https://www.swoft.org/docs/2.x/zh-CN/annotation/index.html

**Comment by onanying** [comment]
现阶段暂时不计划支持，因为mix与swoft他们的目标用户不同，不能把全部框架都做成一样，mix定位更加轻量可定制，如同传统框架的CI
