### ISSUE TITLE
运行官网的websocket的demo 连接成功但response报错

### ISSUE THREAD

**Issue by yaoyingkang** [mix-php/mix#71]
js 发送
连接成功
ws.send('{"method":"join.room","params":[1012,"小明"],"id":1}');

服务端报错
[warning] 2020-01-16 08:14:47.665 <13026> Swoole\Http\Response::close(): http response is unavailable (maybe it has been ended or detached)
[code] 2 [type] Mix\Console\Exception\ErrorException
[file] in /home/vagrant/mix/vendor/mix/websocket/src/Connection.php on line 88
 #0 [internal function]: Mix\Console\Error->appError(2, 'Swoole\\Http\\Res...', '/home/vagrant/m...', 88, Array)
 #1 Swoole\Http\Response->close() in /home/vagrant/mix/vendor/mix/websocket/src/Connection.php on line 88
 #2 Mix\WebSocket\Connection->close() in /home/vagrant/mix/app/WebSocket/Session/Session.php on line 59
 #3 App\WebSocket\Session\Session->clear() in /home/vagrant/mix/app/WebSocket/Handlers/WebSocketHandler.php on line 97
 #4 [internal function]: App\WebSocket\Handlers\WebSocketHandler->__invoke()
 #5 call_user_func(Object(App\WebSocket\Handlers\WebSocketHandler)) in /home/vagrant/mix/app/WebSocket/Commands/StartCommand.php on line 127
 #6 App\WebSocket\Commands\StartCommand->handle(Object(Mix\Http\Message\ServerRequest), Object(Mix\Http\Message\Response)) in /home/vagrant/mix/app/WebSocket/Commands/StartCommand.php on line 91
 #7 [internal function]: App\WebSocket\Commands\StartCommand->App\WebSocket\Commands\{closure}(Object(Mix\Http\Message\ServerRequest), Object(Mix\Http\Message\Response))
 #8 call_user_func(Object(Closure), Object(Mix\Http\Message\ServerRequest), Object(Mix\Http\Message\Response)) in /home/vagrant/mix/vendor/mix/http-server/src/Server.php on line 107
 #9 [internal function]: Mix\Http\Server\Server->Mix\Http\Server\{closure}(Object(Swoole\Http\Request), Object(Swoole\Http\Response))
 #10 {main}

**Comment by onanying** [comment]
@yaoyingkang  这个是 swoole 版本问题，你看下这个 https://github.com/mix-php/mix/blob/master/SWOOLE-CHANGELIST.md， 然后你避开这两个版本即可。

**Comment by yaoyingkang** [comment]
升级swooole版本之后确实可以了  谢谢大佬
