### ISSUE TITLE
PHP用ip curl post请求 会卡1秒

### ISSUE THREAD

**Issue by a6965921** [mix-php/mix#78]
PHP用ip curl post请求 会卡1秒  ip改成域名就不会

**Comment by onanying** [comment]
@a6965921 代码贴一下，说明一下上下文，贴个截图啥的说明一下

**Comment by a6965921** [comment]
跟mixphp代码没关系 任何代码都一样 是运行代码前的延迟 应该跟swoole有关系 我先去测试下swoole是不是也有这个问题

**Comment by a6965921** [comment]
PHP curl 请求 必须是ip 和 post 才会有延迟
  public function submitinforecordzjlist()
    {
        $info = $this->httprepair('http://ip:9501/', array('openid' => 2133), 'post');
        print_r($info);
        exit();
    }
    public function curl_post($url, $data = array())
    {

        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $url);

        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);

        // POST数据

        curl_setopt($ch, CURLOPT_POST, 1);

        // 把post的变量加上

        curl_setopt($ch, CURLOPT_POSTFIELDS, $data);

        $output = curl_exec($ch);

        curl_close($ch);

        return $output;

    }

mixphp
<?php

namespace App\Web\Controllers;

use App\Common\Helpers\ResponseHelper;
use Mix\Database\Database;
use Mix\Http\Message\Response;
use Mix\Http\Message\ServerRequest;

/**
 * Class IndexController
 * @package App\Web\Controllers
 * @author liu,jian <coder.keda@gmail.com>
 */
class IndexController
{

    /**
     * Index
     * @param ServerRequest $request
     * @param Response $response
     * @return Response
     */

    /**
     * @var Database
     */
    public $db;
    public $dd;

    public function __construct()
    {
        $this->db=context()->get('database');
        $this->dd=3;
    }

    public function index(ServerRequest $request, Response $response)
    {
      
        
        $content=$this->dd;
        return ResponseHelper::html($response, $content);
    }

}


收到数据大概1秒后收到  其实代码运行时间是2.3毫秒

我测试过swoole没有这个问题

**Comment by onanying** [comment]
看不明白，完全没明白你测试的是啥

**Comment by onanying** [comment]
![image](https://user-images.githubusercontent.com/16074765/83709186-94aa3a80-a650-11ea-9933-cf642e5304de.png)

如果是请求会超过 1s ，我这里都是正常的，你检查下你环境的原因吧，无法复现。
