### ISSUE TITLE
验证器场景设置optional未生效

### ISSUE THREAD

**Issue by ToBeNoFirst** [mix-php/mix#82]
例如:public function scenarios()
    {
        return [
            'store' => ['required' => ['account'], 'optional' => ['password']],
        ];
    }
在postman中进行测试时,如果password勾选,但值为空,则不会生效
![QQ截图20200807102454](https://user-images.githubusercontent.com/48007465/89602118-9edaf600-d898-11ea-84dc-7c368210e415.png)

**Comment by onanying** [comment]
@ToBeNoFirst 你看一下 message ，这里提示你没有定义 truename 的属性，应该是你的场景包含了这个字段的验证，但是你贴的代码里没有包含 truename ，所以这个我就分析不了了，因为你给的代码给异常提示不匹配，这个问题大概率你解决这个异常就好了

**Comment by ToBeNoFirst** [comment]
![QQ截图20200807102454](https://user-images.githubusercontent.com/48007465/89625658-ccd92e00-d8ca-11ea-9df3-c44fb235f1c6.png)
password传递过来的值是空的,在optional里面填写了,会不验证在vaildtor组件里面BaseValidator.php将这个删除就可以了
![QQ截图20200807102454](https://user-images.githubusercontent.com/48007465/89625944-39ecc380-d8cb-11ea-8974-59c5b85a8297.png)

**Comment by onanying** [comment]
@ToBeNoFirst optional 是可选参数，传入 '' 空字符串，不验证是正常逻辑啊，你修改上面的代码后就会导致传入  ‘’ 空字符串的情况会抛出验证失败，当时加这个就是为了兼容：有些用户喜欢传 ‘’ 空字符串的无用参数
